Config.BlockVault = {
    -- อาวุธ
    ['item_weapon'],
    -- เงิน
    ['money'],
    --
    -- ['aed_untrade'],
    -- ['painkiller_untrade'],
    -- ['armor_untrade'],

    ['plus_p'],
    ['plus_l'],
    ['plus_u'],
    ['plus_s'],
    ['plus_plus'],
    ['plus_t'],
    ['coin_plus'],
    
    ['weaponbox2'],
    ['coin_promote'],
    ['bp_free'],
    ['gangcard'],
    ['familycard'],
    ['aed_warzone'],
    ['pain_warzone'],
    ['armor_warzone'],
    ['box_newplayer'],
    ['armor_dp'],
    ['food_dp'],
    ['radio'],
    ['armoragn'],
    ['car_fam'],
    ['car_gang'],
    ['car_newbie_a'],
    ['coin_c'],
    ['coin_f'],
    ['coin_a'],
    ['coin_g'],
    ['council_coin'],
    ['medic_coin'],
    ['newbiecard'],
    ['newplayer_poolcue_10d'],
    ['painkiller_wz'],
    ['police_coin'],
    ['vault_council'],
    ['vault_key'],
    ['vault_key_pro'],
    ['vault_medic'],
    ['vault_police'],
    -- Newbie
    ['newbie_card'],
    ['reskin_card_newbie'],
    ['newbie_weapon_card'],
    -- Blueprint
    ['blueprint_dagger'],
    ['blueprint_poolcue'],
    ['free_pound'],
    ['box_mother_poolcue_skin'],
    ['box_songkran_poolcue_skin'],
    ['box_songkran_bottle_skin'],
    -- VIP
    ['vip_used'],
    ['box_vip_15d_pack'],
    ['box_vip_7d_pack'],
    ['gacha_vip'],
    ['box_vip_15d'],
    ['box_vip_1d'],
    ['box_vip_7d'],
    ['twitter_vip'],
    -- BOOSTER
    ['box_booster_ss1'],
    ['booter_farm_used'],
    ['booter_fishing_used'],
    ['booter_miner_used'],
    ['box_booter_farm_1d'],
    ['box_booter_farm_1d_pack'],
    ['box_booter_farm_3d'],
    ['box_booter_farm_3d_pack'],
    ['box_booter_farm_7d'],
    ['box_booter_farm_7d_pack'],
    ['box_booter_fishing_1d'],
    ['box_booter_fishing_1d_pack'],
    ['box_booter_fishing_3d'],
    ['box_booter_fishing_3d_pack'],
    ['box_booter_fishing_7d'],
    ['box_booter_fishing_7d_pack'],
    ['box_booter_miner_1d'],
    ['box_booter_miner_1d_pack'],
    ['box_booter_miner_3d'],
    ['box_booter_miner_3d_pack'],
    ['box_booter_miner_7d'],
    ['box_booter_miner_7d_pack'],
    ['twitter_booter'],
    --
    ['coin_revolver'],
    ['coin_weapon'],
    ['coin_weapon2'],
    ['car_sultan3'],
    ['car_2020g900'],
    --
    ['coin_farm'],
    ['coin_plus'],
    ['plus_p'],
    ['plus_l'],
    ['plus_u'],
    ['plus_s'],
    ['plus_plus'],
    ['plus_t'],
    ['reskin'],
    ['box_starterpack'],
    ['box_poolcue_elite'],
}

Config.BypassBlockVault = {
    ['police'] = {
        ['money']
    },
    ['ambulance'] = {
        ['money']
    },
    ['council'] = {
        ['money']
    },
    ['vanilla'] = {
        ['money'],
        ['pub_beer'],
        ['pub_bean'],
        ['radio'],
        ['pub_card'],
        ['condom_plus'],
        ['012wingbutt'],
        ['012wingcyber'],
    },
}

-- Config.GangVaultItem = Config.BlockVault
Config.GangVaultItem = {
    ['aed'],
    ['aed_untrade'],
    ['painkiller_untrade'],
    ['armor_untrade'],
    ['painkiller'],
    ['armor'],
    ['dubsta3'],
    ['sugoi'],
    ['car_sugoi'],
    ['car_dubsta3'],
    ['tk_weapon_ex'],
    ['box_poolcue_elite'],

    ['painkiller_untrade_pack'],
    ['aed_untrade_pack'],
    ['armor_untrade_pack'],
    ['lockpick'],

    ['emp_smoke'],
    ['emp_anticar'],

    ['trade_weapon_elite'],

    ['m_kryptonite'],
    ['m_vibranium'],
    ['m_vibranium_fg'],
    ['m_eternium'],
    ['m_eternium_fg'],
    ['m_auralium'],
    ['m_auralium_fg'],
    ['m_diamond'],
    ['m_diamond_fg'],
    ['m_copper'],
    ['m_copper_box'],
    ['m_gold'],
    ['m_gold_box'],
    ['m_steel'],
    ['m_steel_box'],
    ['black_money'],
    ['board_broke_a'],
    ['board_broke_b'],
    ['board_broke_c'],
    ['board_a'],
    ['lockpick'],
    ['radio'],
    ['aed'],
    ['aed_untrade'],
    ['armor'],
    ['armor_untrade'],
    ['painkiller'],
    ['painkiller_pack'],
    ['painkiller_untrade_pack'],
    ['painkiller_untrade'],
    ['cement'],
    ['cement_pack'],
    ['gang_join'],
    ['gang_leave'],
    ['f_squid'],
    ['f_tuna'],
    ['f_lobster'],
    ['f_crab'],
    ['food_d'],
    ['food_e'],
    ['drink_c'],
    ['food_b'],
    ['drink_b'],
    ['drink_a'],
    ['food_a'],
    ['food_c'],
    ['phone'],
    ['fixkit'],
    ['bag_body'],
    ['m_fiber'],
    ['m_hardened'],
    ['m_polymer'],
    ['m_resin'],
    ['turtle_shell_dust'],
    ['upgrade_s'],
    ['core_a'],
    ['core_b'],
    ['core_c'],


    ['pub_beer'],
    ['pub_bean'],
    ['radio'],
    ['pub_card'],
    ['condom_plus'],
}

Config.VaultNeedItemTake = {
    ['box_poolcue_elite'] = 'trade_weapon_elite',
}

Config.BypassGive = {
    ['council'] = {
        ['gangcard'],
        ['familycard'],
        ['box_welfare_fam'],
        ['box_welfare_gang'],
        ['box_welfare_lady'],
        ['armband_council_a'],
        ['armband_council_b'],
        ['armband_council_c'],
        ['armband_protect'],
        ['armband_story'],
        ['gang_tag_a'],
        ['gang_tag_b'],

    },
    ['police'] = {
        ['take_2'],
        ['attack_police'],
    },
    ['vanilla'] = {
        ['radio'],
        ['mre'],
        ['pub_card'],
        ['pub_beer'],
        ['pub_bean'],
        ['condom_plus'],
    },
}

Config.OnlyGangGive = {
    'painkiller_untrade',
    'aed_untrade',
    'armor_untrade',
    'dubsta3',
    'sugoi',
    'car_sugoi',
    'car_dubsta3',
    'tk_weapon_ex',

    'gang_tag_a',
    'gang_tag_b',

    'painkiller_untrade_pack',
    'aed_untrade_pack',
    'armor_untrade_pack',

    'trade_weapon_elite',

    'emp_smoke',
    'emp_anticar',
}